theme: jekyll-theme-midnight
title: "South Asian Culture Show 2k23"
description: "SACS Family."
gitorg: "https://github.com/RohanG326/jazzyisking"
description: "June 26 to July 1 2023"
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one